// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mahalanobisHelper
SEXP mahalanobisHelper(SEXP data, SEXP index, SEXP invScaleMat);
RcppExport SEXP _optmatch_mahalanobisHelper(SEXP dataSEXP, SEXP indexSEXP, SEXP invScaleMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type index(indexSEXP);
    Rcpp::traits::input_parameter< SEXP >::type invScaleMat(invScaleMatSEXP);
    rcpp_result_gen = Rcpp::wrap(mahalanobisHelper(data, index, invScaleMat));
    return rcpp_result_gen;
END_RCPP
}
// ismOps
SEXP ismOps(SEXP o, SEXP a, SEXP b);
RcppExport SEXP _optmatch_ismOps(SEXP oSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type o(oSEXP);
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(ismOps(o, a, b));
    return rcpp_result_gen;
END_RCPP
}
// r_smahal
SEXP r_smahal(SEXP index, SEXP data, SEXP z);
RcppExport SEXP _optmatch_r_smahal(SEXP indexSEXP, SEXP dataSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type index(indexSEXP);
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(r_smahal(index, data, z));
    return rcpp_result_gen;
END_RCPP
}
// subsetInfSparseMatrix
SEXP subsetInfSparseMatrix(SEXP whichRows, SEXP whichCols, SEXP x);
RcppExport SEXP _optmatch_subsetInfSparseMatrix(SEXP whichRowsSEXP, SEXP whichColsSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type whichRows(whichRowsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type whichCols(whichColsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(subsetInfSparseMatrix(whichRows, whichCols, x));
    return rcpp_result_gen;
END_RCPP
}
