// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mahalanobisHelper
SEXP mahalanobisHelper(SEXP data, SEXP index, SEXP invScaleMat);
RcppExport SEXP optmatch_mahalanobisHelper(SEXP dataSEXP, SEXP indexSEXP, SEXP invScaleMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type index(indexSEXP);
    Rcpp::traits::input_parameter< SEXP >::type invScaleMat(invScaleMatSEXP);
    __result = Rcpp::wrap(mahalanobisHelper(data, index, invScaleMat));
    return __result;
END_RCPP
}
// ismOps
SEXP ismOps(SEXP o, SEXP a, SEXP b);
RcppExport SEXP optmatch_ismOps(SEXP oSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type o(oSEXP);
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    __result = Rcpp::wrap(ismOps(o, a, b));
    return __result;
END_RCPP
}
// r_smahal
SEXP r_smahal(SEXP index, SEXP data, SEXP z);
RcppExport SEXP optmatch_r_smahal(SEXP indexSEXP, SEXP dataSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type index(indexSEXP);
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type z(zSEXP);
    __result = Rcpp::wrap(r_smahal(index, data, z));
    return __result;
END_RCPP
}
// subsetInfSparseMatrix
SEXP subsetInfSparseMatrix(SEXP whichRows, SEXP whichCols, SEXP x);
RcppExport SEXP optmatch_subsetInfSparseMatrix(SEXP whichRowsSEXP, SEXP whichColsSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type whichRows(whichRowsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type whichCols(whichColsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    __result = Rcpp::wrap(subsetInfSparseMatrix(whichRows, whichCols, x));
    return __result;
END_RCPP
}
