# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mahalanobisHelper <- function(data, index, invScaleMat) {
    .Call('optmatch_mahalanobisHelper', PACKAGE = 'optmatch', data, index, invScaleMat)
}

ismOps <- function(o, a, b) {
    .Call('optmatch_ismOps', PACKAGE = 'optmatch', o, a, b)
}

r_smahal <- function(index, data, z) {
    .Call('optmatch_r_smahal', PACKAGE = 'optmatch', index, data, z)
}

subsetInfSparseMatrix <- function(whichRows, whichCols, x) {
    .Call('optmatch_subsetInfSparseMatrix', PACKAGE = 'optmatch', whichRows, whichCols, x)
}

