# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mahalanobisHelper <- function(data, index, invScaleMat) {
    .Call(`_optmatch_mahalanobisHelper`, data, index, invScaleMat)
}

determineGroup <- function(names, compnames) {
    .Call(`_optmatch_determineGroup`, names, compnames)
}

handle_new_cs_cpp <- function(problem, prices, reso, new_c_index) {
    .Call(`_optmatch_handle_new_cs_cpp`, problem, prices, reso, new_c_index)
}

handle_new_ts_cpp <- function(problem, prices, reso, new_t_index) {
    .Call(`_optmatch_handle_new_ts_cpp`, problem, prices, reso, new_t_index)
}

ismOps <- function(o, a, b) {
    .Call(`_optmatch_ismOps`, o, a, b)
}

r_smahal <- function(index, data, z) {
    .Call(`_optmatch_r_smahal`, index, data, z)
}

subsetInfSparseMatrix <- function(whichRows, whichCols, x) {
    .Call(`_optmatch_subsetInfSparseMatrix`, whichRows, whichCols, x)
}

